### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by daPhipz** [andyholmes/gnome-shell-extensions-badge#2]
The link to the page where the official badge should be available (https://gitlab.gnome.org/Teams/Engagement/marketing-design/issues/3) seems to be broken. Have you found an address where it is now?

**Comment by andyholmes** [comment]
I don't have a link to copy on gitlab.gnome.org, sorry! Shortly after it was moved I received a rather unpleasant message from an extension developer, the contents of which aren't really important, but I sort of just dropped the matter after that.

I maintain the repository since I know a number of developers still link to it, but it would probably be best to contact the engagement team directly. Caroline Henriksen produced the image, but Britt Yazel or Sri could also help. I searched through the [Engagement Team](https://gitlab.gnome.org/Teams/Engagement) repository but couldn't find anything. :(

Because the logo includes the GNOME trademark and font it almost certainly licensed as "All rights reserved", as the rest of the engagement materials are. Basically this means you can freely use the logo for the obvious purpose, but you must not make any changes (ie. this is not licensed under the GPL, MIT or CreativeCommons).

**Comment by daPhipz** [comment]
Thanks for the info! I'll have a look myself then ;)
